### ISSUE TITLE
mockyがNot Foundになってしまいました

### ISSUE THREAD

**Issue by coppwii** [mono0926/wdb106-flutter#7]
wdb106を公開してくださり、ありがとうございます。
wdb106を見てFlutterの勉強をさせてもらっています。

現在、wdb106を実行すると、
wdb106で使用している’https://run.mocky.io/v3/6ee7295a-065b-4014-9040-db533ad1389c’が
Not Foundになってしまった為、エラーで実行できなくなりました。

mockyのデータを作成してくださったのがmonoさんかWEB+DB PRESSさんか分かりませんが、
もし直せるなら再度お願いいたします。
(ソースだけでもすごく勉強になりますが、やはり動かした方がわかりやすいので)

**Comment by mono0926** [comment]
@coppwii 

直しました 🐶 👍

**Comment by coppwii** [comment]
monoさん
直してくださり、ありがとうございました。
動作も無事確認できました。
